variables:
  macosSignAndNotarize: false
  isReleaseMode: ${{ and(eq(variables['isReleaseMode'], true), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

jobs:
- job: 'Build_Linux'
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
      BUILD_REASON: $(Build.Reason)
      BRANCH_SHORT_NAME: $(Build.SourceBranchName)
      BRANCH_FULL_NAME: $(Build.SourceBranch)
  steps:
    - checkout: self
      submodules: true

    - script: ./ci/linux/install-dependencies-ubuntu.sh
      displayName: 'Install dependencies'

    - script: ./ci/linux/build-ubuntu.sh
      displayName: 'Build Plugin'

    - script: ./ci/linux/package-ubuntu.sh
      displayName: 'Package Plugin'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './package'
        artifactName: 'deb_build'
